name: CI
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup dummy Google Map API Key
        run: echo "GOOGLE_MAPS_API_KEY=DUMMY" >> Events/gradle.properties
      - name: Build with Gradle
        run: cd Events/app/ && gradle build
